version: "3"
services:
  # mysqlコンテナ定義
  mysql000ex11:
    image: mysql:5.7 # 利用するイメージを指定
    networks: # 接続するネットワークを指定
      - wordpress000net11
    volumes: # 記憶領域のマウントの設定
      - mysql000vol11:/var/lib/mysql
    restart: always # 必ず再起動する
    environment: # 環境変数を設定
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_DATABASE: wordpress000db
      MYSQL_USER: wordpress000kun
      MYSQL_PASSWORD: wkunpass
  # wordpressコンテナ定義
  wordpress000ex12:
    depends_on: # mysql000ex11のコンテナを起動した後に起動
      - mysql000ex11
    image: wordpress
    networks:
      - wordpress000net11
    volumes:
      - wordpress000vol12:/var/www/html
    ports:
      - 8085:80
    restart: always
    environment: # 環境変数を設定
      WORDPRESS_DB_HOST: mysql000ex11
      WORDPRESS_DB_NAME: wordpress000db
      WORDPRESS_DB_USER: wordpress000kun
      WORDPRESS_DB_PASSWORD: wkunpass
networks:
  wordpress000net11:
volumes:
  mysql000vol11:
  wordpress000vol12:
